//
//  AppStoreCountry.swift
//
//
//  Created by Roman Kovalchuk on 13.07.2021.
//

import Foundation

/// Region or country of an App Store in which an app can be available.
///
/// [List of country codes](https://help.apple.com/app-store-connect/#/dev997f9cf7c)
public struct AppStoreCountry: Sendable {
    /// Raw country code. ex. "US" for United States.
    public let code: String?
}

/// Convenience static instances for every supported App Store country or region, named for the
/// country and keyed by the code the iTunes lookup API expects.
public extension AppStoreCountry {
    static let afghanistan: AppStoreCountry = "AFG"
    static let unitedArabEmirates: AppStoreCountry = "AE"
    static let antiguaAndBarbuda: AppStoreCountry = "AG"
    static let anguilla: AppStoreCountry = "AI"
    static let albania: AppStoreCountry = "AL"
    static let armenia: AppStoreCountry = "AM"
    static let angola: AppStoreCountry = "AO"
    static let argentina: AppStoreCountry = "AR"
    static let austria: AppStoreCountry = "AT"
    static let australia: AppStoreCountry = "AU"
    static let azerbaijan: AppStoreCountry = "AZ"
    static let barbados: AppStoreCountry = "BB"
    static let belgium: AppStoreCountry = "BE"
    static let bosniaAndHerzegovina: AppStoreCountry = "BIH"
    static let burkinaFaso: AppStoreCountry = "BF"
    static let bulgaria: AppStoreCountry = "BG"
    static let bahrain: AppStoreCountry = "BH"
    static let benin: AppStoreCountry = "BJ"
    static let bermuda: AppStoreCountry = "BM"
    static let brunei: AppStoreCountry = "BN"
    static let bolivia: AppStoreCountry = "BO"
    static let brazil: AppStoreCountry = "BR"
    static let bahamas: AppStoreCountry = "BS"
    static let bhutan: AppStoreCountry = "BT"
    static let botswana: AppStoreCountry = "BW"
    static let belarus: AppStoreCountry = "BY"
    static let belize: AppStoreCountry = "BZ"
    static let cameroon: AppStoreCountry = "CMR"
    static let canada: AppStoreCountry = "CA"
    static let congoRepublic: AppStoreCountry = "CG"
    static let switzerland: AppStoreCountry = "CH"
    static let coteDIvoire: AppStoreCountry = "CIV"
    static let chile: AppStoreCountry = "CL"
    static let china: AppStoreCountry = "CN"
    static let colombia: AppStoreCountry = "CO"
    static let congoDemocraticRepublic: AppStoreCountry = "COD"
    static let costaRica: AppStoreCountry = "CR"
    static let capeVerde: AppStoreCountry = "CV"
    static let cyprus: AppStoreCountry = "CY"
    static let czechRepublic: AppStoreCountry = "CZ"
    static let germany: AppStoreCountry = "DE"
    static let denmark: AppStoreCountry = "DK"
    static let dominica: AppStoreCountry = "DM"
    static let dominicanRepublic: AppStoreCountry = "DO"
    static let algeria: AppStoreCountry = "DZ"
    static let ecuador: AppStoreCountry = "EC"
    static let estonia: AppStoreCountry = "EE"
    static let egypt: AppStoreCountry = "EG"
    static let spain: AppStoreCountry = "ES"
    static let finland: AppStoreCountry = "FI"
    static let fiji: AppStoreCountry = "FJ"
    static let micronesia: AppStoreCountry = "FM"
    static let france: AppStoreCountry = "FR"
    static let gabon: AppStoreCountry = "GAB"
    static let unitedKingdom: AppStoreCountry = "GB"
    static let grenada: AppStoreCountry = "GD"
    static let georgia: AppStoreCountry = "GEO"
    static let ghana: AppStoreCountry = "GH"
    static let gambia: AppStoreCountry = "GM"
    static let greece: AppStoreCountry = "GR"
    static let guatemala: AppStoreCountry = "GT"
    static let guineaBissau: AppStoreCountry = "GW"
    static let guyana: AppStoreCountry = "GY"
    static let hongKong: AppStoreCountry = "HK"
    static let honduras: AppStoreCountry = "HN"
    static let croatia: AppStoreCountry = "HR"
    static let hungary: AppStoreCountry = "HU"
    static let indonesia: AppStoreCountry = "ID"
    static let ireland: AppStoreCountry = "IE"
    static let israel: AppStoreCountry = "IL"
    static let india: AppStoreCountry = "IN"
    static let iraq: AppStoreCountry = "IRQ"
    static let iceland: AppStoreCountry = "IS"
    static let italy: AppStoreCountry = "IT"
    static let jamaica: AppStoreCountry = "JM"
    static let jordan: AppStoreCountry = "JO"
    static let japan: AppStoreCountry = "JP"
    static let kenya: AppStoreCountry = "KE"
    static let kyrgyzstan: AppStoreCountry = "KG"
    static let cambodia: AppStoreCountry = "KH"
    static let stKittsAndNevis: AppStoreCountry = "KN"
    static let korea: AppStoreCountry = "KR"
    static let kuwait: AppStoreCountry = "KW"
    static let caymanIslands: AppStoreCountry = "KY"
    static let kazakhstan: AppStoreCountry = "KZ"
    static let laos: AppStoreCountry = "LA"
    static let lebanon: AppStoreCountry = "LB"
    static let libya: AppStoreCountry = "LBY"
    static let stLucia: AppStoreCountry = "LC"
    static let sriLanka: AppStoreCountry = "LK"
    static let liberia: AppStoreCountry = "LR"
    static let lithuania: AppStoreCountry = "LT"
    static let luxembourg: AppStoreCountry = "LU"
    static let latvia: AppStoreCountry = "LV"
    static let morocco: AppStoreCountry = "MAR"
    static let moldova: AppStoreCountry = "MD"
    static let maldives: AppStoreCountry = "MDV"
    static let madagascar: AppStoreCountry = "MG"
    static let northMacedonia: AppStoreCountry = "MK"
    static let mali: AppStoreCountry = "ML"
    static let myanmar: AppStoreCountry = "MMR"
    static let mongolia: AppStoreCountry = "MN"
    static let montenegro: AppStoreCountry = "MNE"
    static let macau: AppStoreCountry = "MO"
    static let mauritania: AppStoreCountry = "MR"
    static let montserrat: AppStoreCountry = "MS"
    static let malta: AppStoreCountry = "MT"
    static let mauritius: AppStoreCountry = "MU"
    static let malawi: AppStoreCountry = "MW"
    static let mexico: AppStoreCountry = "MX"
    static let malaysia: AppStoreCountry = "MY"
    static let mozambique: AppStoreCountry = "MZ"
    static let namibia: AppStoreCountry = "NA"
    static let niger: AppStoreCountry = "NE"
    static let nigeria: AppStoreCountry = "NG"
    static let nicaragua: AppStoreCountry = "NI"
    static let netherlands: AppStoreCountry = "NL"
    static let norway: AppStoreCountry = "NO"
    static let nepal: AppStoreCountry = "NP"
    static let nauru: AppStoreCountry = "NRU"
    static let newZealand: AppStoreCountry = "NZ"
    static let oman: AppStoreCountry = "OM"
    static let panama: AppStoreCountry = "PA"
    static let peru: AppStoreCountry = "PE"
    static let papuaNewGuinea: AppStoreCountry = "PG"
    static let philippines: AppStoreCountry = "PH"
    static let pakistan: AppStoreCountry = "PK"
    static let poland: AppStoreCountry = "PL"
    static let portugal: AppStoreCountry = "PT"
    static let palau: AppStoreCountry = "PW"
    static let paraguay: AppStoreCountry = "PY"
    static let qatar: AppStoreCountry = "QA"
    static let romania: AppStoreCountry = "RO"
    static let russia: AppStoreCountry = "RU"
    static let rwanda: AppStoreCountry = "RWA"
    static let saudiArabia: AppStoreCountry = "SA"
    static let solomonIslands: AppStoreCountry = "SB"
    static let seychelles: AppStoreCountry = "SC"
    static let sweden: AppStoreCountry = "SE"
    static let singapore: AppStoreCountry = "SG"
    static let slovenia: AppStoreCountry = "SI"
    static let slovakia: AppStoreCountry = "SK"
    static let sierraLeone: AppStoreCountry = "SL"
    static let senegal: AppStoreCountry = "SN"
    static let suriname: AppStoreCountry = "SR"
    static let serbia: AppStoreCountry = "SRB"
    static let saoTomeAndPrincipe: AppStoreCountry = "ST"
    static let elSalvador: AppStoreCountry = "SV"
    static let swaziland: AppStoreCountry = "SZ"
    static let turksAndCaicosIslands: AppStoreCountry = "TC"
    static let chad: AppStoreCountry = "TD"
    static let thailand: AppStoreCountry = "TH"
    static let tajikistan: AppStoreCountry = "TJ"
    static let turkmenistan: AppStoreCountry = "TM"
    static let tunisia: AppStoreCountry = "TN"
    static let tonga: AppStoreCountry = "TON"
    static let turkey: AppStoreCountry = "TR"
    static let trinidadAndTobago: AppStoreCountry = "TT"
    static let taiwan: AppStoreCountry = "TW"
    static let tanzania: AppStoreCountry = "TZ"
    static let ukraine: AppStoreCountry = "UA"
    static let uganda: AppStoreCountry = "UG"
    static let unitedStates: AppStoreCountry = "US"
    static let uruguay: AppStoreCountry = "UY"
    static let uzbekistan: AppStoreCountry = "UZ"
    static let stVincentAndTheGrenadines: AppStoreCountry = "VC"
    static let venezuela: AppStoreCountry = "VE"
    static let britishVirginIslands: AppStoreCountry = "VG"
    static let vietnam: AppStoreCountry = "VN"
    static let vanuatu: AppStoreCountry = "VUT"
    static let kosovo: AppStoreCountry = "XKS"
    static let yemen: AppStoreCountry = "YE"
    static let southAfrica: AppStoreCountry = "ZA"
    static let zambia: AppStoreCountry = "ZMB"
    static let zimbabwe: AppStoreCountry = "ZW"
}

extension AppStoreCountry: Equatable {}
/// Adds ability to equate instances of `AppStoreCountry` to each other.
/// - Parameters:
///   - lhs: First instance of`AppStoreCountry`
///   - rhs: Second instance of`AppStoreCountry`
/// - Returns: `true` if instances are equal. Otherwise, `false`.
public func == (lhs: AppStoreCountry, rhs: AppStoreCountry) -> Bool {
    lhs.code?.uppercased() == rhs.code?.uppercased()
}

extension AppStoreCountry: ExpressibleByStringLiteral {
    /// Allows for `AppStoreCountry` to be initialized by a string literal.
    /// - Parameter value: An instance of `AppStoreCountry` that can be represented as a `String`.
    public init(stringLiteral value: StringLiteralType) {
        self.init(code: value)
    }
}
